#include "perl6_curl.h"
int perl6_curlinfo_appconnect_time () { return CURLINFO_APPCONNECT_TIME; }
int perl6_curlinfo_certinfo () { return CURLINFO_CERTINFO; }
int perl6_curlinfo_condition_unmet () { return CURLINFO_CONDITION_UNMET; }
int perl6_curlinfo_connect_time () { return CURLINFO_CONNECT_TIME; }
int perl6_curlinfo_content_length_download () { return CURLINFO_CONTENT_LENGTH_DOWNLOAD; }
int perl6_curlinfo_content_length_upload () { return CURLINFO_CONTENT_LENGTH_UPLOAD; }
int perl6_curlinfo_content_type () { return CURLINFO_CONTENT_TYPE; }
int perl6_curlinfo_cookielist () { return CURLINFO_COOKIELIST; }
int perl6_curlinfo_data_in () { return CURLINFO_DATA_IN; }
int perl6_curlinfo_data_out () { return CURLINFO_DATA_OUT; }
int perl6_curlinfo_double () { return CURLINFO_DOUBLE; }
int perl6_curlinfo_effective_url () { return CURLINFO_EFFECTIVE_URL; }
int perl6_curlinfo_end () { return CURLINFO_END; }
int perl6_curlinfo_filetime () { return CURLINFO_FILETIME; }
int perl6_curlinfo_ftp_entry_path () { return CURLINFO_FTP_ENTRY_PATH; }
int perl6_curlinfo_header_in () { return CURLINFO_HEADER_IN; }
int perl6_curlinfo_header_out () { return CURLINFO_HEADER_OUT; }
int perl6_curlinfo_header_size () { return CURLINFO_HEADER_SIZE; }
int perl6_curlinfo_httpauth_avail () { return CURLINFO_HTTPAUTH_AVAIL; }
int perl6_curlinfo_http_code () { return CURLINFO_HTTP_CODE; }
int perl6_curlinfo_http_connectcode () { return CURLINFO_HTTP_CONNECTCODE; }
int perl6_curlinfo_lastone () { return CURLINFO_LASTONE; }
int perl6_curlinfo_lastsocket () { return CURLINFO_LASTSOCKET; }
int perl6_curlinfo_local_ip () { return CURLINFO_LOCAL_IP; }
int perl6_curlinfo_local_port () { return CURLINFO_LOCAL_PORT; }
int perl6_curlinfo_long () { return CURLINFO_LONG; }
int perl6_curlinfo_mask () { return CURLINFO_MASK; }
int perl6_curlinfo_namelookup_time () { return CURLINFO_NAMELOOKUP_TIME; }
int perl6_curlinfo_none () { return CURLINFO_NONE; }
int perl6_curlinfo_num_connects () { return CURLINFO_NUM_CONNECTS; }
int perl6_curlinfo_os_errno () { return CURLINFO_OS_ERRNO; }
int perl6_curlinfo_pretransfer_time () { return CURLINFO_PRETRANSFER_TIME; }
int perl6_curlinfo_primary_ip () { return CURLINFO_PRIMARY_IP; }
int perl6_curlinfo_primary_port () { return CURLINFO_PRIMARY_PORT; }
int perl6_curlinfo_private () { return CURLINFO_PRIVATE; }
int perl6_curlinfo_proxyauth_avail () { return CURLINFO_PROXYAUTH_AVAIL; }
int perl6_curlinfo_redirect_count () { return CURLINFO_REDIRECT_COUNT; }
int perl6_curlinfo_redirect_time () { return CURLINFO_REDIRECT_TIME; }
int perl6_curlinfo_redirect_url () { return CURLINFO_REDIRECT_URL; }
int perl6_curlinfo_request_size () { return CURLINFO_REQUEST_SIZE; }
int perl6_curlinfo_response_code () { return CURLINFO_RESPONSE_CODE; }
int perl6_curlinfo_rtsp_client_cseq () { return CURLINFO_RTSP_CLIENT_CSEQ; }
int perl6_curlinfo_rtsp_cseq_recv () { return CURLINFO_RTSP_CSEQ_RECV; }
int perl6_curlinfo_rtsp_server_cseq () { return CURLINFO_RTSP_SERVER_CSEQ; }
int perl6_curlinfo_rtsp_session_id () { return CURLINFO_RTSP_SESSION_ID; }
int perl6_curlinfo_size_download () { return CURLINFO_SIZE_DOWNLOAD; }
int perl6_curlinfo_size_upload () { return CURLINFO_SIZE_UPLOAD; }
int perl6_curlinfo_slist () { return CURLINFO_SLIST; }
int perl6_curlinfo_speed_download () { return CURLINFO_SPEED_DOWNLOAD; }
int perl6_curlinfo_speed_upload () { return CURLINFO_SPEED_UPLOAD; }
int perl6_curlinfo_ssl_data_in () { return CURLINFO_SSL_DATA_IN; }
int perl6_curlinfo_ssl_data_out () { return CURLINFO_SSL_DATA_OUT; }
int perl6_curlinfo_ssl_engines () { return CURLINFO_SSL_ENGINES; }
int perl6_curlinfo_ssl_verifyresult () { return CURLINFO_SSL_VERIFYRESULT; }
int perl6_curlinfo_starttransfer_time () { return CURLINFO_STARTTRANSFER_TIME; }
int perl6_curlinfo_string () { return CURLINFO_STRING; }
int perl6_curlinfo_text () { return CURLINFO_TEXT; }
int perl6_curlinfo_total_time () { return CURLINFO_TOTAL_TIME; }
int perl6_curlinfo_typemask () { return CURLINFO_TYPEMASK; }
int perl6_curlopttype_functionpoint () { return CURLOPTTYPE_FUNCTIONPOINT; }
int perl6_curlopttype_long () { return CURLOPTTYPE_LONG; }
int perl6_curlopttype_objectpoint () { return CURLOPTTYPE_OBJECTPOINT; }
int perl6_curlopttype_off_t () { return CURLOPTTYPE_OFF_T; }
int perl6_curlopt_accepttimeout_ms () { return CURLOPT_ACCEPTTIMEOUT_MS; }
int perl6_curlopt_accept_encoding () { return CURLOPT_ACCEPT_ENCODING; }
int perl6_curlopt_address_scope () { return CURLOPT_ADDRESS_SCOPE; }
int perl6_curlopt_append () { return CURLOPT_APPEND; }
int perl6_curlopt_autoreferer () { return CURLOPT_AUTOREFERER; }
int perl6_curlopt_buffersize () { return CURLOPT_BUFFERSIZE; }
int perl6_curlopt_cainfo () { return CURLOPT_CAINFO; }
int perl6_curlopt_capath () { return CURLOPT_CAPATH; }
int perl6_curlopt_certinfo () { return CURLOPT_CERTINFO; }
int perl6_curlopt_chunk_bgn_function () { return CURLOPT_CHUNK_BGN_FUNCTION; }
int perl6_curlopt_chunk_data () { return CURLOPT_CHUNK_DATA; }
int perl6_curlopt_chunk_end_function () { return CURLOPT_CHUNK_END_FUNCTION; }
int perl6_curlopt_closepolicy () { return CURLOPT_CLOSEPOLICY; }
int perl6_curlopt_closesocketdata () { return CURLOPT_CLOSESOCKETDATA; }
int perl6_curlopt_closesocketfunction () { return CURLOPT_CLOSESOCKETFUNCTION; }
int perl6_curlopt_connecttimeout () { return CURLOPT_CONNECTTIMEOUT; }
int perl6_curlopt_connecttimeout_ms () { return CURLOPT_CONNECTTIMEOUT_MS; }
int perl6_curlopt_connect_only () { return CURLOPT_CONNECT_ONLY; }
int perl6_curlopt_conv_from_network_function () { return CURLOPT_CONV_FROM_NETWORK_FUNCTION; }
int perl6_curlopt_conv_from_utf8_function () { return CURLOPT_CONV_FROM_UTF8_FUNCTION; }
int perl6_curlopt_conv_to_network_function () { return CURLOPT_CONV_TO_NETWORK_FUNCTION; }
int perl6_curlopt_cookie () { return CURLOPT_COOKIE; }
int perl6_curlopt_cookiefile () { return CURLOPT_COOKIEFILE; }
int perl6_curlopt_cookiejar () { return CURLOPT_COOKIEJAR; }
int perl6_curlopt_cookielist () { return CURLOPT_COOKIELIST; }
int perl6_curlopt_cookiesession () { return CURLOPT_COOKIESESSION; }
int perl6_curlopt_copypostfields () { return CURLOPT_COPYPOSTFIELDS; }
int perl6_curlopt_crlf () { return CURLOPT_CRLF; }
int perl6_curlopt_crlfile () { return CURLOPT_CRLFILE; }
int perl6_curlopt_customrequest () { return CURLOPT_CUSTOMREQUEST; }
int perl6_curlopt_debugdata () { return CURLOPT_DEBUGDATA; }
int perl6_curlopt_debugfunction () { return CURLOPT_DEBUGFUNCTION; }
int perl6_curlopt_dirlistonly () { return CURLOPT_DIRLISTONLY; }
int perl6_curlopt_dns_cache_timeout () { return CURLOPT_DNS_CACHE_TIMEOUT; }
int perl6_curlopt_dns_servers () { return CURLOPT_DNS_SERVERS; }
int perl6_curlopt_dns_use_global_cache () { return CURLOPT_DNS_USE_GLOBAL_CACHE; }
int perl6_curlopt_egdsocket () { return CURLOPT_EGDSOCKET; }
int perl6_curlopt_encoding () { return CURLOPT_ENCODING; }
int perl6_curlopt_errorbuffer () { return CURLOPT_ERRORBUFFER; }
int perl6_curlopt_failonerror () { return CURLOPT_FAILONERROR; }
int perl6_curlopt_file () { return CURLOPT_FILE; }
int perl6_curlopt_filetime () { return CURLOPT_FILETIME; }
int perl6_curlopt_fnmatch_data () { return CURLOPT_FNMATCH_DATA; }
int perl6_curlopt_fnmatch_function () { return CURLOPT_FNMATCH_FUNCTION; }
int perl6_curlopt_followlocation () { return CURLOPT_FOLLOWLOCATION; }
int perl6_curlopt_forbid_reuse () { return CURLOPT_FORBID_REUSE; }
int perl6_curlopt_fresh_connect () { return CURLOPT_FRESH_CONNECT; }
int perl6_curlopt_ftpappend () { return CURLOPT_FTPAPPEND; }
int perl6_curlopt_ftplistonly () { return CURLOPT_FTPLISTONLY; }
int perl6_curlopt_ftpport () { return CURLOPT_FTPPORT; }
int perl6_curlopt_ftpsslauth () { return CURLOPT_FTPSSLAUTH; }
int perl6_curlopt_ftp_account () { return CURLOPT_FTP_ACCOUNT; }
int perl6_curlopt_ftp_alternative_to_user () { return CURLOPT_FTP_ALTERNATIVE_TO_USER; }
int perl6_curlopt_ftp_create_missing_dirs () { return CURLOPT_FTP_CREATE_MISSING_DIRS; }
int perl6_curlopt_ftp_filemethod () { return CURLOPT_FTP_FILEMETHOD; }
int perl6_curlopt_ftp_response_timeout () { return CURLOPT_FTP_RESPONSE_TIMEOUT; }
int perl6_curlopt_ftp_skip_pasv_ip () { return CURLOPT_FTP_SKIP_PASV_IP; }
int perl6_curlopt_ftp_ssl () { return CURLOPT_FTP_SSL; }
int perl6_curlopt_ftp_ssl_ccc () { return CURLOPT_FTP_SSL_CCC; }
int perl6_curlopt_ftp_use_eprt () { return CURLOPT_FTP_USE_EPRT; }
int perl6_curlopt_ftp_use_epsv () { return CURLOPT_FTP_USE_EPSV; }
int perl6_curlopt_ftp_use_pret () { return CURLOPT_FTP_USE_PRET; }
int perl6_curlopt_gssapi_delegation () { return CURLOPT_GSSAPI_DELEGATION; }
int perl6_curlopt_header () { return CURLOPT_HEADER; }
int perl6_curlopt_headerdata () { return CURLOPT_HEADERDATA; }
int perl6_curlopt_headerfunction () { return CURLOPT_HEADERFUNCTION; }
int perl6_curlopt_http200aliases () { return CURLOPT_HTTP200ALIASES; }
int perl6_curlopt_httpauth () { return CURLOPT_HTTPAUTH; }
int perl6_curlopt_httpget () { return CURLOPT_HTTPGET; }
int perl6_curlopt_httpheader () { return CURLOPT_HTTPHEADER; }
int perl6_curlopt_httppost () { return CURLOPT_HTTPPOST; }
int perl6_curlopt_httpproxytunnel () { return CURLOPT_HTTPPROXYTUNNEL; }
int perl6_curlopt_http_content_decoding () { return CURLOPT_HTTP_CONTENT_DECODING; }
int perl6_curlopt_http_transfer_decoding () { return CURLOPT_HTTP_TRANSFER_DECODING; }
int perl6_curlopt_http_version () { return CURLOPT_HTTP_VERSION; }
int perl6_curlopt_ignore_content_length () { return CURLOPT_IGNORE_CONTENT_LENGTH; }
int perl6_curlopt_infile () { return CURLOPT_INFILE; }
int perl6_curlopt_infilesize () { return CURLOPT_INFILESIZE; }
int perl6_curlopt_infilesize_large () { return CURLOPT_INFILESIZE_LARGE; }
int perl6_curlopt_interface () { return CURLOPT_INTERFACE; }
int perl6_curlopt_interleavedata () { return CURLOPT_INTERLEAVEDATA; }
int perl6_curlopt_interleavefunction () { return CURLOPT_INTERLEAVEFUNCTION; }
int perl6_curlopt_ioctldata () { return CURLOPT_IOCTLDATA; }
int perl6_curlopt_ioctlfunction () { return CURLOPT_IOCTLFUNCTION; }
int perl6_curlopt_ipresolve () { return CURLOPT_IPRESOLVE; }
int perl6_curlopt_issuercert () { return CURLOPT_ISSUERCERT; }
int perl6_curlopt_keypasswd () { return CURLOPT_KEYPASSWD; }
int perl6_curlopt_krb4level () { return CURLOPT_KRB4LEVEL; }
int perl6_curlopt_krblevel () { return CURLOPT_KRBLEVEL; }
int perl6_curlopt_localport () { return CURLOPT_LOCALPORT; }
int perl6_curlopt_localportrange () { return CURLOPT_LOCALPORTRANGE; }
int perl6_curlopt_low_speed_limit () { return CURLOPT_LOW_SPEED_LIMIT; }
int perl6_curlopt_low_speed_time () { return CURLOPT_LOW_SPEED_TIME; }
int perl6_curlopt_mail_auth () { return CURLOPT_MAIL_AUTH; }
int perl6_curlopt_mail_from () { return CURLOPT_MAIL_FROM; }
int perl6_curlopt_mail_rcpt () { return CURLOPT_MAIL_RCPT; }
int perl6_curlopt_maxconnects () { return CURLOPT_MAXCONNECTS; }
int perl6_curlopt_maxfilesize () { return CURLOPT_MAXFILESIZE; }
int perl6_curlopt_maxfilesize_large () { return CURLOPT_MAXFILESIZE_LARGE; }
int perl6_curlopt_maxredirs () { return CURLOPT_MAXREDIRS; }
int perl6_curlopt_max_recv_speed_large () { return CURLOPT_MAX_RECV_SPEED_LARGE; }
int perl6_curlopt_max_send_speed_large () { return CURLOPT_MAX_SEND_SPEED_LARGE; }
int perl6_curlopt_netrc () { return CURLOPT_NETRC; }
int perl6_curlopt_netrc_file () { return CURLOPT_NETRC_FILE; }
int perl6_curlopt_new_directory_perms () { return CURLOPT_NEW_DIRECTORY_PERMS; }
int perl6_curlopt_new_file_perms () { return CURLOPT_NEW_FILE_PERMS; }
int perl6_curlopt_nobody () { return CURLOPT_NOBODY; }
int perl6_curlopt_noprogress () { return CURLOPT_NOPROGRESS; }
int perl6_curlopt_noproxy () { return CURLOPT_NOPROXY; }
int perl6_curlopt_nosignal () { return CURLOPT_NOSIGNAL; }
int perl6_curlopt_opensocketdata () { return CURLOPT_OPENSOCKETDATA; }
int perl6_curlopt_opensocketfunction () { return CURLOPT_OPENSOCKETFUNCTION; }
int perl6_curlopt_password () { return CURLOPT_PASSWORD; }
int perl6_curlopt_port () { return CURLOPT_PORT; }
int perl6_curlopt_post () { return CURLOPT_POST; }
int perl6_curlopt_post301 () { return CURLOPT_POST301; }
int perl6_curlopt_postfields () { return CURLOPT_POSTFIELDS; }
int perl6_curlopt_postfieldsize () { return CURLOPT_POSTFIELDSIZE; }
int perl6_curlopt_postfieldsize_large () { return CURLOPT_POSTFIELDSIZE_LARGE; }
int perl6_curlopt_postquote () { return CURLOPT_POSTQUOTE; }
int perl6_curlopt_postredir () { return CURLOPT_POSTREDIR; }
int perl6_curlopt_prequote () { return CURLOPT_PREQUOTE; }
int perl6_curlopt_private () { return CURLOPT_PRIVATE; }
int perl6_curlopt_progressdata () { return CURLOPT_PROGRESSDATA; }
int perl6_curlopt_progressfunction () { return CURLOPT_PROGRESSFUNCTION; }
int perl6_curlopt_protocols () { return CURLOPT_PROTOCOLS; }
int perl6_curlopt_proxy () { return CURLOPT_PROXY; }
int perl6_curlopt_proxyauth () { return CURLOPT_PROXYAUTH; }
int perl6_curlopt_proxypassword () { return CURLOPT_PROXYPASSWORD; }
int perl6_curlopt_proxyport () { return CURLOPT_PROXYPORT; }
int perl6_curlopt_proxytype () { return CURLOPT_PROXYTYPE; }
int perl6_curlopt_proxyusername () { return CURLOPT_PROXYUSERNAME; }
int perl6_curlopt_proxyuserpwd () { return CURLOPT_PROXYUSERPWD; }
int perl6_curlopt_proxy_transfer_mode () { return CURLOPT_PROXY_TRANSFER_MODE; }
int perl6_curlopt_put () { return CURLOPT_PUT; }
int perl6_curlopt_quote () { return CURLOPT_QUOTE; }
int perl6_curlopt_random_file () { return CURLOPT_RANDOM_FILE; }
int perl6_curlopt_range () { return CURLOPT_RANGE; }
int perl6_curlopt_readdata () { return CURLOPT_READDATA; }
int perl6_curlopt_readfunction () { return CURLOPT_READFUNCTION; }
int perl6_curlopt_redir_protocols () { return CURLOPT_REDIR_PROTOCOLS; }
int perl6_curlopt_referer () { return CURLOPT_REFERER; }
int perl6_curlopt_resolve () { return CURLOPT_RESOLVE; }
int perl6_curlopt_resume_from () { return CURLOPT_RESUME_FROM; }
int perl6_curlopt_resume_from_large () { return CURLOPT_RESUME_FROM_LARGE; }
int perl6_curlopt_rtspheader () { return CURLOPT_RTSPHEADER; }
int perl6_curlopt_rtsp_client_cseq () { return CURLOPT_RTSP_CLIENT_CSEQ; }
int perl6_curlopt_rtsp_request () { return CURLOPT_RTSP_REQUEST; }
int perl6_curlopt_rtsp_server_cseq () { return CURLOPT_RTSP_SERVER_CSEQ; }
int perl6_curlopt_rtsp_session_id () { return CURLOPT_RTSP_SESSION_ID; }
int perl6_curlopt_rtsp_stream_uri () { return CURLOPT_RTSP_STREAM_URI; }
int perl6_curlopt_rtsp_transport () { return CURLOPT_RTSP_TRANSPORT; }
int perl6_curlopt_seekdata () { return CURLOPT_SEEKDATA; }
int perl6_curlopt_seekfunction () { return CURLOPT_SEEKFUNCTION; }
int perl6_curlopt_server_response_timeout () { return CURLOPT_SERVER_RESPONSE_TIMEOUT; }
int perl6_curlopt_share () { return CURLOPT_SHARE; }
int perl6_curlopt_sockoptdata () { return CURLOPT_SOCKOPTDATA; }
int perl6_curlopt_sockoptfunction () { return CURLOPT_SOCKOPTFUNCTION; }
int perl6_curlopt_socks5_gssapi_nec () { return CURLOPT_SOCKS5_GSSAPI_NEC; }
int perl6_curlopt_socks5_gssapi_service () { return CURLOPT_SOCKS5_GSSAPI_SERVICE; }
int perl6_curlopt_ssh_auth_types () { return CURLOPT_SSH_AUTH_TYPES; }
int perl6_curlopt_ssh_host_public_key_md5 () { return CURLOPT_SSH_HOST_PUBLIC_KEY_MD5; }
int perl6_curlopt_ssh_keydata () { return CURLOPT_SSH_KEYDATA; }
int perl6_curlopt_ssh_keyfunction () { return CURLOPT_SSH_KEYFUNCTION; }
int perl6_curlopt_ssh_knownhosts () { return CURLOPT_SSH_KNOWNHOSTS; }
int perl6_curlopt_ssh_private_keyfile () { return CURLOPT_SSH_PRIVATE_KEYFILE; }
int perl6_curlopt_ssh_public_keyfile () { return CURLOPT_SSH_PUBLIC_KEYFILE; }
int perl6_curlopt_sslcert () { return CURLOPT_SSLCERT; }
int perl6_curlopt_sslcertpasswd () { return CURLOPT_SSLCERTPASSWD; }
int perl6_curlopt_sslcerttype () { return CURLOPT_SSLCERTTYPE; }
int perl6_curlopt_sslengine () { return CURLOPT_SSLENGINE; }
int perl6_curlopt_sslengine_default () { return CURLOPT_SSLENGINE_DEFAULT; }
int perl6_curlopt_sslkey () { return CURLOPT_SSLKEY; }
int perl6_curlopt_sslkeypasswd () { return CURLOPT_SSLKEYPASSWD; }
int perl6_curlopt_sslkeytype () { return CURLOPT_SSLKEYTYPE; }
int perl6_curlopt_sslversion () { return CURLOPT_SSLVERSION; }
int perl6_curlopt_ssl_cipher_list () { return CURLOPT_SSL_CIPHER_LIST; }
int perl6_curlopt_ssl_ctx_data () { return CURLOPT_SSL_CTX_DATA; }
int perl6_curlopt_ssl_ctx_function () { return CURLOPT_SSL_CTX_FUNCTION; }
int perl6_curlopt_ssl_options () { return CURLOPT_SSL_OPTIONS; }
int perl6_curlopt_ssl_sessionid_cache () { return CURLOPT_SSL_SESSIONID_CACHE; }
int perl6_curlopt_ssl_verifyhost () { return CURLOPT_SSL_VERIFYHOST; }
int perl6_curlopt_ssl_verifypeer () { return CURLOPT_SSL_VERIFYPEER; }
int perl6_curlopt_stderr () { return CURLOPT_STDERR; }
int perl6_curlopt_tcp_keepalive () { return CURLOPT_TCP_KEEPALIVE; }
int perl6_curlopt_tcp_keepidle () { return CURLOPT_TCP_KEEPIDLE; }
int perl6_curlopt_tcp_keepintvl () { return CURLOPT_TCP_KEEPINTVL; }
int perl6_curlopt_tcp_nodelay () { return CURLOPT_TCP_NODELAY; }
int perl6_curlopt_telnetoptions () { return CURLOPT_TELNETOPTIONS; }
int perl6_curlopt_tftp_blksize () { return CURLOPT_TFTP_BLKSIZE; }
int perl6_curlopt_timecondition () { return CURLOPT_TIMECONDITION; }
int perl6_curlopt_timeout () { return CURLOPT_TIMEOUT; }
int perl6_curlopt_timeout_ms () { return CURLOPT_TIMEOUT_MS; }
int perl6_curlopt_timevalue () { return CURLOPT_TIMEVALUE; }
int perl6_curlopt_tlsauth_password () { return CURLOPT_TLSAUTH_PASSWORD; }
int perl6_curlopt_tlsauth_type () { return CURLOPT_TLSAUTH_TYPE; }
int perl6_curlopt_tlsauth_username () { return CURLOPT_TLSAUTH_USERNAME; }
int perl6_curlopt_transfertext () { return CURLOPT_TRANSFERTEXT; }
int perl6_curlopt_transfer_encoding () { return CURLOPT_TRANSFER_ENCODING; }
int perl6_curlopt_unrestricted_auth () { return CURLOPT_UNRESTRICTED_AUTH; }
int perl6_curlopt_upload () { return CURLOPT_UPLOAD; }
int perl6_curlopt_url () { return CURLOPT_URL; }
int perl6_curlopt_useragent () { return CURLOPT_USERAGENT; }
int perl6_curlopt_username () { return CURLOPT_USERNAME; }
int perl6_curlopt_userpwd () { return CURLOPT_USERPWD; }
int perl6_curlopt_use_ssl () { return CURLOPT_USE_SSL; }
int perl6_curlopt_verbose () { return CURLOPT_VERBOSE; }
int perl6_curlopt_wildcardmatch () { return CURLOPT_WILDCARDMATCH; }
int perl6_curlopt_writedata () { return CURLOPT_WRITEDATA; }
int perl6_curlopt_writefunction () { return CURLOPT_WRITEFUNCTION; }
int perl6_curlopt_writeheader () { return CURLOPT_WRITEHEADER; }
int perl6_curlopt_writeinfo () { return CURLOPT_WRITEINFO; }
